namespace Wsh.UIAnimation.Easing {

    public enum EasingType {
        IN_SINE         = 1,
        OUT_SINE        = 2,
        INOUT_SINE      = 3,
        IN_QUAD         = 4,
        OUT_QUAD        = 5,
        INOUT_QUAD      = 6,
        IN_CUBIC        = 7,
        OUT_CUBIC       = 8,
        INOUT_CUBIC     = 9,
        IN_QUART        = 10,
        OUT_QUART       = 11,
        INOUT_QUART     = 12,
        IN_QUINT        = 13,
        OUT_QUINT       = 14,
        INOUT_QUINT     = 15,
        IN_EXPO         = 16,
        OUT_EXPO        = 17,
        INOUT_EXPO      = 18,
        IN_CIRC         = 19,
        OUT_CIRC        = 20,
        INOUT_CIRC      = 21,
        IN_BACK         = 22,
        OUT_BACK        = 23,
        INOUT_BACK      = 24,
        IN_ELASTIC      = 25,
        OUT_ELASTIC     = 26,
        INOUT_ELASTIC   = 27,
        IN_BOUNCE       = 28,
        OUT_BOUNCE      = 29,
        INOUT_BOUNCE    = 30,
        LINE            = 1000,
    }
}